db:
  Password: "123qwe"
  User: "social"
  Port: "3306"
  Host: "0.0.0.0"
  DbName: "socialdb"
  MaxOpenConnection: 100
  MaxOpenIdleConnection: 10
  ConnMaxLifetime: 3
  MigrationPath: "./db/migrations"