server:
  StartDelay: 0
  Host: "0.0.0.0"
  Port: "3005"
db:
  Password: "alsdgkjsadf"
  User: "social"
  Port: "3306"
  Host: "0.0.0.0"
  DbName: "socialdb"
  MaxOpenConnection: 100
  MaxOpenIdleConnection: 100
  ConnMaxLifetime: 10
  MigrationPath: "./migrations"