Server:
  StartDelay: 0
  Host: "0.0.0.0"
  Port: "3005"
Protection:
  AllowOrigins:
    - "http://localhost:3000"
    - "http://localhost"
Db:
  Password: "alsdgkjsadf"
  User: "social"
  Port: "6033"
  Host: "127.0.0.1"
  DbName: "socialdb"
  MaxOpenConnection: 100
  MaxOpenIdleConnection: 100
  ConnMaxLifetime: 10
  MigrationPath: "./migrations"
Broker:
    BrokerUrls:
      - "localhost:49171"
      - "localhost:43173"
      - "localhost:43175"
    PostTopic:
      Name: "topic-post"
      NumPartitions: 2
      ReplicationFactor: 3