server:
  StartDelay: 0
  Host: "0.0.0.0"
  Port: "3005"
Protection:
  AllowOrigins:
    - "http://localhost:3000"
    - "http://localhost"
db:
  Password: "xylsalsdjfl"
  User: "root"
  Port: "6033"
  Host: "127.0.0.1"
  DbName: "socialdb"
  MaxOpenConnection: 100
  MaxOpenIdleConnection: 100
  ConnMaxLifetime: 10
  MigrationPath: "./migrations"