db:
  Password: "alsdgkjsadf"
  User: "social"
  Port: "3306"
  Host: "db"
  DbName: "socialdb"
  MaxOpenConnection: 100
  MaxOpenIdleConnection: 100
  ConnMaxLifetime: 10
  MigrationPath: "./migrations"