Server:
  Host: "0.0.0.0"
  Port: "3007"
Protection:
  AllowOrigins:
    - "https://localhost:3000"
    - "https://localhost"
Db:
  Password: "alsdgkjsadf"
  User: "social"
  Port: "6033"
  Host: "127.0.0.1"
  DbName: "socialdb"
  MaxOpenConnection: 100
  MaxOpenIdleConnection: 100
  ConnMaxLifetime: 10
Broker:
  BrokerUrls:
    - "localhost:49171"
    - "localhost:43173"
  PostTopic:
    Name: "topic-post"
    NumPartitions: 2
    ReplicationFactor: 2