version: "3.8"

services:
  db:
    container_name: social-db
    image: sigma-social-db
    volumes:
      - social-db-data:/var/lib/mysql
      - social-db-log:/var/log/mysql
    networks:
      - sigma_net
    ports:
      - "3306:3306"

  db-replica-1:
    depends_on:
      - db
    container_name: db-replica-1
    image: sigma-social-db-replica-1
    volumes:
      - social-db-replica-1-data:/var/lib/mysql
      - social-db-replica-1-log:/var/log/mysql
    networks:
      - sigma_net
    ports:
      - "3305:3306"

  db-replica-2:
    container_name: db-replica-2
    image: sigma-social-db-replica-2
    volumes:
      - social-db-replica-2-data:/var/lib/mysql
      - social-db-replica-2-log:/var/log/mysql
    networks:
      - sigma_net
    ports:
      - "3304:3306"

  db-proxysql:
    depends_on:
      - db
      - db-replica-1
      - db-replica-2
    container_name: db-proxy
    image: sigma-db-proxy
    networks:
      - sigma_net
    ports:
      # Mysql Client Port
      - "6033:6033"
      # Mysql Admin Port
      - "6032:6032"
      # Web
      - "6080:6080"

  zookeeper:
    container_name: zookeeper
    image: bitnami/zookeeper:latest
    networks:
      - sigma_net
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka-1:
    container_name: broker-1
    image: bitnami/kafka:latest
    networks:
      - sigma_net
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_LISTENERS=CLIENT://:49170,EXTERNAL://:49171
      - KAFKA_CFG_ADVERTISED_LISTENERS=CLIENT://kafka-1:49170,EXTERNAL://localhost:49171
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=CLIENT
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    ports:
      - "49170:49170"
      - "49171:49171"
    depends_on:
      - zookeeper

  kafka-2:
    container_name: broker-2
    image: bitnami/kafka:latest
    networks:
      - sigma_net
    environment:
      - KAFKA_BROKER_ID=2
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_LISTENERS=CLIENT://:49172,EXTERNAL://:49173
      - KAFKA_CFG_ADVERTISED_LISTENERS=CLIENT://kafka-2:49172,EXTERNAL://localhost:49173
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=CLIENT
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    ports:
      - "49172:49172"
      - "49173:49173"
    depends_on:
      - zookeeper

networks:
  sigma_net:
    external: true
    name: sigma_net

volumes:
  social-db-data:
    name: social-db-data
  social-db-log:
    name: social-db-log
  social-db-replica-1-data:
    name: social-db-replica-1-data
  social-db-replica-2-data:
    name: social-db-replica-2-data
  social-db-replica-1-log:
    name: social-db-replica-1-log
  social-db-replica-2-log:
    name: social-db-replica-2-log